# ansible
#
# Dockerfile for building Ansible image from source for Ubuntu 14.04 (trusty), with as few additional software as possible.
#
# @see http://docs.ansible.com/ansible/intro_installation.html#running-from-source
#
# VERSION               0.0.1
# From: https://hub.docker.com/r/williamyeh/ansible/~/dockerfile/

FROM ubuntu/sshd:20.04

LABEL org.opencontainers.image.authors="Nelson Goncalves <nelson.goncalves.fr@gmail.com>"


RUN echo "===> Install ansible..."     && \
    apt update -y                                     && \
    apt upgrade -y                                    && \
    DEBIAN_FRONTEND=noninteractive                       \
        apt install --no-install-recommends -y -q        \
                build-essential python3-pip              \
                sshpass openssh-client                && \
    pip install ansible==2.10.7                       && \
    apt clean                                         && \
    rm -rf /var/lib/apt/lists/*

RUN echo "===> Adding hosts for convenience..."  && \
    mkdir -p /etc/ansible                        && \
    echo 'localhost' > /etc/ansible/hosts

RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa

ENV PATH        /opt/ansible/bin:$PATH
ENV PYTHONPATH  /opt/ansible/lib:$PYTHONPATH
ENV MANPATH     /opt/ansible/docs/man:$MANPATH

# default command: display Ansible version
CMD [ "ansible-playbook", "--version" ]
