version: '2'
services:
  ansible:
    image: ubuntu/ansible:24.04
    container_name: ansible
    hostname: ansible
    command: /usr/sbin/sshd -D
    volumes:
      - .:/home/ansible
    working_dir: /home/ansible
    networks:
      ansible_tuto:
        ipv4_address: 172.16.238.5
    links:
      - host0
      - host1
      - host2
  host0:
    image: ubuntu/sshd:24.04
    container_name: host0
    hostname: host0
    networks:
      ansible_tuto:
        ipv4_address: 172.16.238.10
  host1:
    image: ubuntu/sshd:24.04
    container_name: host1
    hostname: host1
    networks:
      ansible_tuto:
        ipv4_address: 172.16.238.11
  host2:
    image: ubuntu/sshd:24.04
    container_name: host2
    hostname: host2
    networks:
      ansible_tuto:
        ipv4_address: 172.16.238.12

networks:
  ansible_tuto:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
