- hosts: all
  become: yes
  become_user: root
  remote_user: root

  tasks:
    - name: Is rsa file exists ?
      local_action: stat path=~/.ssh/id_rsa.pub
      run_once: true
      register: st_rsa

    - local_action: fail msg="No key found (rsa or dsa), use tool ssh-keygen to create one"
      run_once: true
      when: st_rsa.stat.exists == False

    - name: Creates destination directory
      file: state=directory mode=0700 dest=/root/.ssh/

    - name: Pushes user's rsa key to root's docker container (it's ok if this TASK fails)
      copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      register: rsa
      ignore_errors: yes
